[package]
name = "maxio-common"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
chrono.workspace = true
uuid.workspace = true
bytes.workspace = true
quick-xml.workspace = true
