[package]
name = "maxio-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
aes-gcm = "0.10"
rand = "0.8"
sha2 = "0.10"
base64 = "0.22"
hkdf = "0.12"
thiserror = { workspace = true }
